# README

Simulated sequecnes were generated using generated_apples_and_oranges.ipynb in this repo

lastz and minimap2 alignmnets between simulated sequecnes were generated using Galaxy and can be found in this history: https://usegalaxy.org/u/cartman/h/simulated-runs

The resulting files `minimap2.paf` and `lastz.general` are also found in this repo

Fastga alignments were generating by cloning `170a178d` version of https://github.com/thegenemyers/FASTGA and running the following command:

```
$ FastGA -T8 -i.6 orange.indels.fa apple.indels.fa > fastga.paf
```

In [158]:
import pandas as pd
import altair as alt

In [173]:
# Check that query and target are from the same length and divergence group
# e.g., ORANGE_id97_len10000 == APPLE_id97_len10000

def check_suffix_match_by_slice(df, col1, col2, n1, n2):
    s1 = df[col1].str[n1:]  # drop the first `n` characters in each value
    s2 = df[col2].str[n2:]
    df['match'] = (s1 == s2)
    print
    print(f"Numberf of mismatches = {len(df[df['match'] == False])}")
    return df

# Extract length and identity values from sequence Ids
# e.g., APPLE_id97_len10000 is parsed into two additional 
# columns with values 97 (% identity) and 10000 (seqence length)

def extract_id_len(df: pd.DataFrame,
                            source_col: str,
                            id_col: str = 'identity',
                            length_col: str = 'length') -> pd.DataFrame:
    """
    Extract numeric values after 'id' and 'len' from a string column into two integer columns.

    Parameters
    ----------
    df : pd.DataFrame
        Input DataFrame.
    source_col : str
        Name of the column containing strings like 'APPLE_id100_len1000'.
    id_col : str, default 'identity'
        Name of the new column for the extracted 'id' number.
    length_col : str, default 'length'
        Name of the new column for the extracted 'len' number.

    Returns
    -------
    pd.DataFrame
        The same DataFrame with two new integer columns (in place).
    """
    # perform extraction with named groups, then convert to int
    df[[id_col, length_col]] = (
        df[source_col]
          .str.extract(r'id(?P<{}>\d+)_len(?P<{}>\d+)$'.format(id_col, length_col))
          .astype(int)
    )
    return df

# Resolves overlapping genomic intervals by computing union

def merge_genomic_intervals(df: pd.DataFrame,
                            chrom_col: str = 'chrom',
                            start_col: str = 'start',
                            end_col: str = 'end',
                            closed: str = 'both') -> pd.DataFrame:
    """
    Merge overlapping or adjacent genomic intervals per chromosome.

    Parameters
    ----------
    df : pd.DataFrame
        Input table with at least columns for chromosome, start, end.
    chrom_col : str
        Name of the chromosome column.
    start_col : str
        Name of the start‐coordinate column.
    end_col : str
        Name of the end‐coordinate column.
    closed : {'both','left','right','neither'}
        Interval closure rule for pandas.Interval.

    Returns
    -------
    pd.DataFrame
        Merged intervals with columns [chrom, start, end].
    """
    # keep only the columns we need
    df = df[[chrom_col, start_col, end_col]].copy()
    df['interval'] = pd.IntervalIndex.from_arrays(
        df[start_col], df[end_col], closed=closed
    )

    def _merge(group):
        group = group.sort_values(start_col)
        merged = []
        curr = group.iloc[0].interval
        for iv in group.interval.iloc[1:]:
            # overlap or exactly adjacent?
            if curr.overlaps(iv) or (curr.right + 1 == iv.left):
                curr = pd.Interval(
                    min(curr.left, iv.left),
                    max(curr.right, iv.right),
                    closed=closed
                )
            else:
                merged.append(curr)
                curr = iv
        merged.append(curr)
        return pd.DataFrame({
            start_col: [iv.left for iv in merged],
            end_col:   [iv.right for iv in merged]
        })

    # groupby on the chrom key, but only hand apply the relevant cols to .apply()
    merged = (
        df[[start_col, end_col, 'interval']]
        .groupby(df[chrom_col])
        .apply(_merge)
        .reset_index(level=1, drop=True)
        .rename_axis(chrom_col)
        .reset_index()
    )

    print(f"Before merging = {len(df)}, After merging = {len(merged)}")
    return merged

# Group by refernece to sum length of alignments within a single fragement

def group_and_report(df, group_col='t', sum_col='align_len'):
    """
    Group df by `group_col`, sum `sum_col`, 
    print row‐counts before & after, and return the grouped df.
    """
    before = len(df)
    # perform the group+sum (avoids the FutureWarning by using the 'sum' string)
    grouped = (
        df
        .groupby(group_col, as_index=False)
        .agg({sum_col: 'sum'})
    )
    after = len(grouped)
    
    print(f"Before grouping = {before}, After grouping = {after}")
    return grouped

def process_aligner_pafs(file, aligner_name, extract_cols, col_q='q', col_t='t', sep='\t'):
    df = pd.read_csv(file, sep=sep, names=extract_cols)
    df = check_suffix_match_by_slice(df, col_t, col_q, 6, 7)
    df = df[[col_t, 'start', 'end']]
    df = merge_genomic_intervals(df, col_t)
    df['align_len'] = df['end'] - df['start'] + 1
    agg = group_and_report(df)
    agg = extract_id_len(agg, col_t)
    agg['aligner'] = aligner_name
    return agg

## Prep lastz output

In [160]:
# Remove "%" from columns of lastz output
!awk 'BEGIN{FS=OFS="\t"} {gsub(/%/, "", $13); gsub(/%/, "", $15); print}' ../alignments/lastz.general > ../scratch/lz.tsv

In [161]:
!head -n 2 ../scratch/lz.tsv

93266	APPLE_id100_len1000	+	3000	1000	2003	ORANGE_id100_len1000	-	3011	1000	2014	1002/1003	99.9	1003/3000	33.4
184118	APPLE_id100_len2000	+	4000	1000	3000	ORANGE_id100_len2000	+	4029	1000	3029	1999/2000	100.0	2000/4000	50.0

In [162]:
lz = pd.read_csv('../scratch/lz.tsv',sep='\t',names="score,t,strand1,size1,start,end,name2,strand2,size2,zstart2,end2,identity_rat,identity,coverage_rat,cvrg".split(","))

In [163]:
lz.head()

,score,t,strand1,size1,start,end,name2,strand2,size2,zstart2,end2,identity_rat,identity,coverage_rat,cvrg
0,93266,APPLE_id100_len1000,+,3000,1000,2003,ORANGE_id100_len1000,-,3011,1000,2014,1002/1003,99.9,1003/3000,33.4
1,184118,APPLE_id100_len2000,+,4000,1000,3000,ORANGE_id100_len2000,+,4029,1000,3029,1999/2000,100.0,2000/4000,50.0
2,459054,APPLE_id100_len5000,+,7000,1000,6029,ORANGE_id100_len5000,+,7080,1000,6110,5017/5029,99.8,5029/7000,71.8
3,918611,APPLE_id100_len10000,+,12000,1000,11001,ORANGE_id100_len10000,+,12176,1000,11177,9997/10001,100.0,10001/12000,83.3
4,89388,APPLE_id99_len1000,+,3000,1000,2007,ORANGE_id99_len1000,-,3019,1000,2027,995/1007,98.8,1007/3000,33.6

In [164]:
lz = check_suffix_match_by_slice(lz, 't', 'name2', 6, 7)

Numberf of mismatches = 0

In [165]:
lz = lz[['t','start','end']].sort_values(by=['t','start'])

In [166]:
lz = merge_genomic_intervals(lz,'t','start','end','left')

Before merging = 164, After merging = 164

In [167]:
lz['align_len'] = lz['end']-lz['start']+1

In [168]:
lz_agg = group_and_report(lz)

Before grouping = 164, After grouping = 164

In [169]:
lz_agg = extract_id_len(lz_agg,'t')

In [170]:
lz_agg.head()

                      t  align_len  identity  length
0   APPLE_id100_len1000       1004       100    1000
1  APPLE_id100_len10000      10002       100   10000
2   APPLE_id100_len2000       2001       100    2000
3   APPLE_id100_len5000       5030       100    5000
4    APPLE_id60_len1000        992        60    1000

In [171]:
lz_agg['aligner']='lastz'

In [172]:
lz_agg.head()

                      t  align_len  identity  length aligner
0   APPLE_id100_len1000       1004       100    1000   lastz
1  APPLE_id100_len10000      10002       100   10000   lastz
2   APPLE_id100_len2000       2001       100    2000   lastz
3   APPLE_id100_len5000       5030       100    5000   lastz
4    APPLE_id60_len1000        992        60    1000   lastz

## Process minimap2 and fastGa output

In [190]:
mm_agg = process_aligner_pafs('../scratch/mm.tsv','minimap2','q,t,start,end'.split(','))

Numberf of mismatches = 0
Before merging = 92, After merging = 92
Before grouping = 92, After grouping = 92

In [206]:
fga_agg = process_aligner_pafs('../scratch/fga.tsv','fastga','q,t,start,end'.split(','))

Numberf of mismatches = 0
Before merging = 158, After merging = 158
Before grouping = 158, After grouping = 130

## Processing last output

```
lastdb -uMAM8 -P 32 -c apples apple.indels.fa 
last-train -P 32 apples orange.indels.fa > oranges_apples.train
lastal -p oranges_apples.train apples orange.indels.fa -f BlastTab+ > ../alignments/last.tsv
```

In [207]:
!grep -v '^#' ../alignments/last.tsv | cut -f 1,2,3,4,9,10 > ../scratch/last.tsv

In [208]:
!head -n 2 ../scratch/last.tsv

ORANGE_id100_len1000	APPLE_id100_len1000	98.82	1014	1001	2003
ORANGE_id100_len2000	APPLE_id100_len2000	98.52	2029	1001	3000

In [209]:
last = pd.read_csv('../scratch/last.tsv',sep='\t',names='q,t,identity,align_len,start,end'.split(','))

In [210]:
last.head()

,q,t,identity,align_len,start,end
0,ORANGE_id100_len1000,APPLE_id100_len1000,98.82,1014,1001,2003
1,ORANGE_id100_len2000,APPLE_id100_len2000,98.52,2029,1001,3000
2,ORANGE_id100_len5000,APPLE_id100_len5000,98.41,5083,1001,6003
3,ORANGE_id100_len10000,APPLE_id100_len10000,98.24,10177,1001,11001
4,ORANGE_id99_len1000,APPLE_id99_len1000,97.06,1020,1001,2001

In [211]:
last = check_suffix_match_by_slice(last, 't', 'q', 6, 7)

Numberf of mismatches = 0

In [212]:
last = last[['t','start','end']].sort_values(by=['t','start'])

In [213]:
last = merge_genomic_intervals(last,'t','start','end','left')

Before merging = 196, After merging = 196

In [214]:
last['align_len'] = last['end']-last['start']+1

In [215]:
last_agg = group_and_report(last)

Before grouping = 196, After grouping = 164

In [216]:
last_agg = extract_id_len(last_agg,'t')

In [217]:
last_agg['aligner']='last'

In [218]:
last.head()

                      t  start    end  align_len
0   APPLE_id100_len1000   1001   2003       1003
1  APPLE_id100_len10000   1001  11001      10001
2   APPLE_id100_len2000   1001   3000       2000
3   APPLE_id100_len5000   1001   6003       5003
4    APPLE_id60_len1000   1096   1406        311

## Plotting

In [219]:
data = pd.concat([lz_agg,mm_agg,fga_agg,last_agg], ignore_index=True)

In [221]:
data['labels'] = data['t'].str[6:]

In [222]:
data['coverage']=data['align_len']/data['length']

In [223]:
alt.Chart(data).mark_circle(size=100).encode(
    x=alt.X('identity:O').axis(title=None),#, sort=sorted_apple),
    y=alt.Y('coverage:Q').axis(title=None),
    color=alt.Color('aligner:N',sort=['lastz','fastga','minimap2','last'],title='Aligner'),
    row=alt.Row('length:N',title=None),
    #column='divergence:O'
).properties(
    width=800,  # Set width of the chart
    height=50,  # Set height of the chart,
).resolve_scale(
    x='independent'  # Make x-axis independent across columns
)

alt.Chart(...)

In [ ]:
data

In [ ]:
data[(data['aligner']=='fastga') & (data['length']==5000)]